name: PR

on:
  pull_request:
    branches:[ "main" ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@4
        with:
          python-version: 3.9
      - name: Run python script
        run: |
          echo run hello_world.py
          python hello_world.py
        
